#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#


name: Refresh CDN
on:
  push:
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Refresh CDN
        run : |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"

          curl -L "https://purge.jsdelivr.net/gh/jeremyfa/yaml.js@develop/dist/yaml.min.js"
          curl -L "https://purge.jsdelivr.net/gh/wjz304/Redpill_CustomBuild@main/.github/workflows/custom.yml"
          curl -L "https://purge.jsdelivr.net/gh/pocopico/rp-ext@main/redpill/rpext-index.json"
          curl -L "https://purge.jsdelivr.net/gh/wjz304/rp-ext@main/redpill/rpext-index.json"
          curl -L "https://purge.jsdelivr.net/gh/wjz304/Redpill_CustomBuild@main/exts.json"
          curl -L "https://purge.jsdelivr.net/npm/marked/marked.min.js"
          curl -L "https://purge.jsdelivr.net/gh/wjz304/Redpill_CustomBuild@main/tips.md"